- .devops/deploy-pipelines.yml
- .gitignore
- helm/Chart.lock
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
> PGEC-74 new deploy pipeline

- README.md
- openapi/openapi.json
> Added README

- openapi/openapi.json
- src/main/java/it/gov/pagopa/afm/calculator/controller/CalculatorController.java
> fix maxOccurrences

- .devops/deploy-pipelines.yml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
> Fix CD pipeline

- .devops/deploy-pipelines.yml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi-node.json
- openapi/openapi.json
- pom.xml
- src/test/java/it/gov/pagopa/afm/calculator/ApplicationTest.java
- src/test/resources/application.properties
> CD pipeline

- .devops/deploy-pipelines.yml
- perf-tests/README.md
The goal of this PR is to update the deploy pipeline.
pipeline tested ✅
> fix deploy

- src/main/java/it/gov/pagopa/afm/calculator/entity/Bundle.java
- src/main/java/it/gov/pagopa/afm/calculator/model/bundle/BundleInfo.java
depends on https://github.com/pagopa/pagopa-afm-marketplace-be/pull/48
- added idChannel
- added idBrokerPsp
- added digitalStamp
- added digitaleStampRestriction
- added onUs
> feat: [PGEC-86] Added info to bundle

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
> added affinity

- .github/workflows/integration_test.yml
- .github/workflows/release_deploy.yml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- integration-test/src/config/.env.dev
- integration-test/src/features/getFeeByPsp.feature
- integration-test/src/features/getFees.feature
- integration-test/src/step_definitions/support/common.js
- integration-test/src/step_definitions/support/steps.js
- openapi/openapi-node.json
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/afm/calculator/controller/CalculatorController.java
- src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOption.java
- src/main/java/it/gov/pagopa/afm/calculator/model/PaymentOptionByPsp.java
- src/main/java/it/gov/pagopa/afm/calculator/model/PspSearchCriteria.java
- src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
- src/main/java/it/gov/pagopa/afm/calculator/util/CriteriaBuilder.java
- src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
- src/test/resources/requests/getFeesPspList.json
- changed psp search criteria for the GetFees and GetFeesByPsp methods
- with the only idPsp search criteria more results could be returned; This was not always a desired behavior
Junit and manual test
> Pagopa 749 psp channel broker

- .github/workflows/check_pr.yml
- .github/workflows/code_review.yml
- .github/workflows/create_dashboard.yaml
- .github/workflows/deploy_with_github_runner.yml
- .github/workflows/integration_test.yml
- .github/workflows/release_deploy.yml
- .github/workflows/update_code.yml
- .gitignore
- .identity/00_data.tf
- .identity/02_application_action.tf
- .identity/03_github_environment.tf
- .identity/99_variables.tf
- .identity/README.md
- helm/Chart.lock
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- integration-test/src/step_definitions/support/steps.js
- openapi/openapi-node.json
- openapi/openapi.json
- pom.xml
> Canary and Actions

- .github/workflows/check_pr.yml
- .github/workflows/integration_test.yml
- .github/workflows/release_deploy.yml
- .identity/00_data.tf
- .identity/02_application_action.tf
- .identity/03_github_environment.tf
- .identity/README.md
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi-node.json
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/afm/calculator/controller/CalculatorController.java
- src/main/java/it/gov/pagopa/afm/calculator/controller/ConfigurationController.java
- src/main/java/it/gov/pagopa/afm/calculator/model/calculator/Transfer.java
- src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
- src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
- src/main/java/it/gov/pagopa/afm/calculator/service/ConfigurationService.java
- src/main/java/it/gov/pagopa/afm/calculator/service/IssuersService.java
- src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
> new workflow

- .github/workflows/create_dashboard.yaml
- .github/workflows/deploy_with_github_runner.yml
- .github/workflows/release_deploy.yml
- README.md
> Small changes

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi-node.json
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/afm/calculator/controller/CalculatorController.java
- src/test/java/it/gov/pagopa/afm/calculator/controller/CalculatorControllerTest.java
This PR contains the new feature related to the new flag for hide bundles related to Poste. This feature follows the same logic related to `POST /fees` API. 
- Added flag for hiding bundle related to Poste 
This changes is required in order to permits the obfuscation of Poste bundles.
- Tested in local environment
- Tested in DEV environment
> [PAGOPA-1023] feat: set allCCP flag on get-fees-by-psp API

- src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
- managed null value in the bundle
- null pointer exception error when flag digitalStamp is set to true
Manual and Junit test
> bug: [PAGOPA-1205] digitalstamp exception

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi-node.json
- openapi/openapi.json
- pom.xml
> fix: Upd helm chart

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
> fix: Ingress port

- .github/workflows/code_review.yml
- .github/workflows/update_code.yml
- Dockerfile
- README.md
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi-node.json
- openapi/openapi.json
- pom.xml
Moving to java 17
Needed in order to use a not deprecated jdk
Tested manually
> PAGOPA-1470 moving to java 17

- src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
Fix shuffle error
Bug fix
Manually
> fix shuffle error

- helm/values-prod.yaml
> chore: Upd prod helm

- .opex/internal/v1/env/prod/config.yaml
- .opex/internal/v2/env/prod/backend.tfvars
- .opex/internal/v2/env/prod/config.yaml
- .opex/node/v1/env/prod/config.yaml
- .opex/node/v2/env/prod/backend.tfvars
- .opex/node/v2/env/prod/config.yaml
> chore: Upd opex

- openapi/openapi-v1.json
> chore: Fix remove acutor from openapi

- helm/values-dev.yaml
> chore: Fix dev helm

- .opex/internal/v1/env/prod/config.yaml
- .opex/internal/v2/env/prod/config.yaml
- .opex/node/v1/env/prod/config.yaml
- .opex/node/v2/env/prod/config.yaml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi-node-v1.json
- openapi/openapi-node-v2.json
- openapi/openapi-v1-dev-uat.json
- openapi/openapi-v1.json
- openapi/openapi-v2.json
- pom.xml
- src/main/java/it/gov/pagopa/afm/calculator/config/LoggingAspect.java
- src/main/java/it/gov/pagopa/afm/calculator/exception/AppError.java
Changing pointers of opex dashboard from app-gateway to apim
Change needed to properly record the calls made to afm-calculator
Manually
> PAGOPA-1761 changing pointers from app-gw to apim

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
> update config map

- scripts/updateABI/listTable.py
- scripts/updateABI/updateTable.py
Adding scripts for the ABI update action
Needed to update Intesa ABI 
Manually
> Pagopa 1955 afm modifica abi intesa prod

- scripts/updateABI/listABICosmos.py
- scripts/updateABI/updateABICosmos.py
Adding scripts python to update cosmos collection
Needed in order to manually intervene on cosmos collection
Manually
> feat: adding scripts to list and update abi in cosmos collection MAIN-24

- src/main/java/it/gov/pagopa/afm/calculator/model/TransferListItem.java
- src/main/java/it/gov/pagopa/afm/calculator/service/UtilityComponent.java
- src/test/java/it/gov/pagopa/afm/calculator/service/UtilityComponentTest.java
✨ Add taxonomy extraction logic.
[PIDM-112](https://pagopa.atlassian.net/browse/PIDM-112)
🤖 Junit
[PIDM-112]: https://pagopa.atlassian.net/browse/PIDM-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(UtilityComponent.java): improve taxonomy value extraction [PIDM-112]

- .github/workflows/code_review.yml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- integration-test/src/config/data.json
- integration-test/src/features/getFeeByPsp.feature
- openapi/openapi-node-v1.json
- openapi/openapi-node-v2.json
- openapi/openapi-v1-dev-uat.json
- openapi/openapi-v1.json
- openapi/openapi-v2.json
- pom.xml
- src/main/java/it/gov/pagopa/afm/calculator/config/SwaggerConfig.java
- src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
- src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
- src/test/java/it/gov/pagopa/afm/calculator/OpenApiGenerationTest.java
- src/test/java/it/gov/pagopa/afm/calculator/TestUtil.java
- src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
- retrieved onUs value from DB field instead of check id channel value
- updated unit tests
- fixed openapi generation
- update transfer category list filter when input is null
[PAGOPA-2721](https://pagopa.atlassian.net/browse/PAGOPA-2721)
[PAGOPA-2721]: https://pagopa.atlassian.net/browse/PAGOPA-2721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PAOGPA-2721] feat: Update onUs computation

- helm/values-prod.yaml
- src/main/resources/application.properties
- Update log level
- Update Helm values prod
Needed in order to lower consumption
Manually
> chore: Fix helm and log level

- Dockerfile
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi-node-v1.json
- openapi/openapi-node-v2.json
- openapi/openapi-v1-dev-uat.json
- openapi/openapi-v1.json
- openapi/openapi-v2.json
- pom.xml
> chore: change docker image to 2.2.7

- openapi/openapi-node-v2.json
- openapi/openapi-v2.json
update openapi queryparams for sorting bundles
[PAGOPA-3104] (https://pagopa.atlassian.net/jira/software/c/projects/PAGOPA/boards/336?selectedIssue=PAGOPA-3104)
[PAGOPA-3104]: https://pagopa.atlassian.net/jira/software/c/projects/PAGOPA/boards/336?selectedIssue=PAGOPA-3104
> [PAGOPA-3104] fix: update openapi queryparams

- src/main/java/it/gov/pagopa/afm/calculator/model/TransferListItem.java
> fix: rollback transferCategory notNull

- src/main/java/it/gov/pagopa/afm/calculator/service/CalculatorService.java
- src/test/java/it/gov/pagopa/afm/calculator/service/CalculatorServiceTest.java
- fix issuers list clear 
- add parsing control to bin value
Needed in order to fix a bug in the main version: issuers list must be mutable
Manually and through junit tests
> Fix issuer list

- integration-test/src/features/getPaymentMethodsRangeAmount.feature
- integration-test/src/features/getPaymentMethodsTotalAmount.feature
- integration-test/src/features/getPaymentMethodsUserDeviceKo.feature
- integration-test/src/features/getPaymentMethodsUserDeviceOk.feature
- integration-test/src/features/getPaymentMethodsUserTouchpointKo.feature
- integration-test/src/features/getPaymentMethodsUserTouchpointOk.feature
- openapi/openapi-internal.json
- openapi/openapi-node-v1.json
- openapi/openapi-node-v2.json
- openapi/openapi-v1-dev-uat.json
- openapi/openapi-v1.json
- openapi/openapi-v2.json
- src/main/java/it/gov/pagopa/afm/calculator/model/paymentmethods/PaymentMethodRequest.java
- src/main/java/it/gov/pagopa/afm/calculator/service/PaymentMethodsService.java
- src/test/resources/requests/paymentOptionsSearch.json
- Removed bin field from searchPaymentMethods
- Updated openapi
- Updated unit tests
- Updated integration tests
[PAGOPA-3272](https://pagopa.atlassian.net/browse/PAGOPA-3272)
Unit tests
[PAGOPA-3273]: https://pagopa.atlassian.net/browse/PAGOPA-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PAGOPA-3272]: https://pagopa.atlassian.net/browse/PAGOPA-3272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [PAGOPA-3272] Remove bin field from searchPaymentMethods

- src/main/java/it/gov/pagopa/afm/calculator/repository/CosmosRepository.java
- src/test/java/it/gov/pagopa/afm/calculator/repository/CosmosRepositoryTest.java
🐞 This PR fix the bug with the `transferlist` filter
> hotfix filter pm
